Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
print("Let's learn Pytorch")

Let's learn Pytorch


In [2]:
import torch
print(torch.__version__)

2.7.0+cpu


In [3]:
## Introduction to Tensors

#creating tensor

In [4]:
scaler = torch.tensor(1)
scaler

tensor(1)

In [5]:
scaler.ndim

0

In [6]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [7]:
vector.ndim

1

In [8]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
matrix.ndim

2

In [10]:
tensor = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
tensor.shape

torch.Size([1, 3, 3])

In [12]:
tensor.ndim

3

In [13]:
sword = torch.tensor(
    [[[[1,2],
       [3,4],
       [5,6]]]]
)
sword

tensor([[[[1, 2],
          [3, 4],
          [5, 6]]]])

In [14]:
sword.ndim

4

In [15]:
sword.shape

torch.Size([1, 1, 3, 2])

In [16]:
a = torch.tensor( [
    [ [1,2,3],
     [2,4,6],
      [3,6,9]],

    [ [3,2,1],
     [6, 4, 2],
      [9,6,3]]
])
a.shape

torch.Size([2, 3, 3])

In [17]:
# make a tensor of torch.Size([1,2,3])

b = torch.tensor([
    [
    [1,2,3],
    [4,5,6]
]
])
b.shape

torch.Size([1, 2, 3])

### why Random Tensors ?
Random tensors are important because the way neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2974, 0.4498, 0.1022, 0.0055],
        [0.5180, 0.6498, 0.8736, 0.8244],
        [0.2240, 0.9038, 0.7019, 0.0102]])

In [19]:
random_tensor.ndim

2

In [20]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size =(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [21]:
random_image_size_tensor

tensor([[[0.0624, 0.4218, 0.2246,  ..., 0.7797, 0.2300, 0.0573],
         [0.0514, 0.4578, 0.3847,  ..., 0.1807, 0.5681, 0.8050],
         [0.4896, 0.2216, 0.1639,  ..., 0.9063, 0.7378, 0.0154],
         ...,
         [0.0649, 0.9909, 0.3246,  ..., 0.3542, 0.4431, 0.4180],
         [0.7857, 0.6886, 0.9777,  ..., 0.3808, 0.4675, 0.5631],
         [0.8066, 0.3528, 0.3662,  ..., 0.6678, 0.6180, 0.5764]],

        [[0.0155, 0.4283, 0.4548,  ..., 0.9507, 0.3189, 0.1464],
         [0.2993, 0.9530, 0.5402,  ..., 0.6948, 0.7815, 0.2889],
         [0.2767, 0.6911, 0.8492,  ..., 0.3513, 0.5692, 0.3929],
         ...,
         [0.8505, 0.1478, 0.9626,  ..., 0.5758, 0.0221, 0.5147],
         [0.4372, 0.4162, 0.9257,  ..., 0.1427, 0.7283, 0.4154],
         [0.2487, 0.5379, 0.5505,  ..., 0.6811, 0.7360, 0.9557]],

        [[0.6298, 0.3051, 0.4025,  ..., 0.5555, 0.9831, 0.8781],
         [0.1917, 0.4030, 0.0030,  ..., 0.2582, 0.4874, 0.7260],
         [0.1241, 0.4301, 0.7525,  ..., 0.8837, 0.7552, 0.

### Creating random tensors with value 0 or 1

In [22]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros = zeros + random_tensor
zeros

tensor([[0.2974, 0.4498, 0.1022, 0.0055],
        [0.5180, 0.6498, 0.8736, 0.8244],
        [0.2240, 0.9038, 0.7019, 0.0102]])

In [24]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating a tensor range and tensors like other tensors

In [26]:
# Use torch.range()

# torch.range(1,100)
# works but it is deprecated. so, we'll use torch.arange

one_to_ten = torch.arange(start =0, end =11, step=1)

In [27]:
one_to_ten.shape

torch.Size([11])

In [28]:
# Creating tensors like
ten_zeros = torch.zeros_like(input =one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Dealing with Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [29]:
# Float 32 tensor
float_32_tensor = torch.tensor([4.0,5.0,2.0],
                               dtype=None, #What dataType is the tensor
                               device = None, # what device is your tensor on
                               requires_grad=False # whether or not to track gradients with the tensor operations
                               )

float_16_tensor = torch.tensor([1.2,3.1,5.5],
                               dtype= torch.float16, #What dataType is the tensor
                               device = None, # what device is your tensor on
                               requires_grad=False # whether or not to track gradients with the tensor operations
                               )
float_32_tensor

tensor([4., 5., 2.])

In [30]:
float_32_tensor.dtype

torch.float32

### Getting Tensor Attributes

In [31]:
float_16_tensor * float_32_tensor

tensor([ 4.8008, 15.4980, 11.0000])

In [32]:
int_32_tensor = torch.tensor([4,6,7], dtype=torch.int64)

In [33]:
float_32_tensor * int_32_tensor

tensor([16., 30., 14.])

### Getting Information from tensors
1. Tensors not right datatype -> to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape -> to get shape from tensor, can use `tensor.shape`
3. Tensors not on the right device -> to get device from a tensor, can use `tensor.device`

In [34]:
# create a tensor

some_tensor = torch.rand(2,4)
some_tensor

tensor([[0.3329, 0.3491, 0.2234, 0.1730],
        [0.6398, 0.6530, 0.7108, 0.0518]])

In [35]:
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([2, 4])
cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication


In [36]:
# Create a tensor and perform basic arithmetic operations

tensor = torch.tensor([1,2,3])
print("Sum: ",tensor+10) #torch.sum(tensor,10)
print("Difference: ",tensor-1) #torch.diff(tensor,1)
print("Product: ",tensor*10) #torch.mul(tensor,10)
print("Division: ",tensor/2) #torch.divide(tensor,2)

Sum:  tensor([11, 12, 13])
Difference:  tensor([0, 1, 2])
Product:  tensor([10, 20, 30])
Division:  tensor([0.5000, 1.0000, 1.5000])


### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise Multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The `Inner Dimension` must match:

- `(3,2) & (3,2)` won't work
- `(3,2) & (2,3)` will work
- `(3,2) & (2,3)` will work

2. The resulting matrix has a shape of **outer dimensions**:
- `(2,3) & (3,2)` -> (2,2)
- `(3,2) & (2,3)` -> (3,3)

In [37]:
# Element wise multiplication
print("tensor * tensor")
print(tensor * tensor)

tensor * tensor
tensor([1, 4, 9])


In [38]:
# Matrix multiplication

print("tensor to tensor matrix multiplication")
print(torch.matmul(tensor,tensor))

tensor to tensor matrix multiplication
tensor(14)


In [39]:
m1 = torch.rand(2,3)
m2 = torch.rand(2,3)

print(m1)
print(m2)

tensor([[0.3117, 0.0615, 0.9207],
        [0.8113, 0.4721, 0.8688]])
tensor([[0.8315, 0.7254, 0.2810],
        [0.9003, 0.0896, 0.5442]])


In [40]:
# torch.matmul(m1,m2)
torch.matmul(m1,m2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
a = torch.rand(3,2)
b = torch.rand(2,3)
# If you notice you'll see, shape of two matrices. row of mat1 and column of mat2 is shape of matrix multiplication
torch.matmul(a,b)

tensor([[0.7609, 0.5051, 0.3691],
        [0.4306, 0.3259, 0.1767],
        [0.4564, 0.3416, 0.1904]])

### One of the most common errors in deep learning: Shape Errors

In [ ]:
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]
])

# torch.matmul == torch.mm
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**

A transpose switches the axes or dimension of a given tensor

In [ ]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
print(f"Original shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.T.shape}")

Original shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([2, 3])


In [ ]:
torch.mm(tensor_A,tensor_B.T
         )

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

### finding the min, max, mean, sum, etc (Tensor Aggregation)

In [ ]:
data = torch.arange(0,105,5)
# When datatype is not specified, it assigns Long and gives error which giving mean value.
data

tensor([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
         60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [ ]:
print("min",data.min())
print("max",data.max())
print("mean", torch.mean(data.type(torch.float32)))
print("median",data.median())
print("min",data.sum())

min tensor(0.)
max tensor(100.)
mean tensor(50.)
median tensor(50.)
min tensor(1050.)


In [ ]:
data.type(torch.float32).mean()

tensor(50.)

### Finding the Positional Min and Max of Tensors

In [ ]:
# find the position in tensor that has the minimum value with argmin() -> returns index of min value from the tensor.
data.argmin()


tensor(0)

In [ ]:
# find the position in tensor that has the maxiumu value with argmax() -> returns index of max value from the tensor.
data.argmax()


tensor(20)