Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

### Note
**I left errors in some place intentionally, because error can teach you more than a working code can do.**

In [193]:
print("Let's learn Pytorch")

Let's learn Pytorch


In [194]:
import torch
print(torch.__version__)

2.7.0+cpu


In [195]:
## Introduction to Tensors

#creating tensor

In [196]:
scaler = torch.tensor(1)
scaler

tensor(1)

In [197]:
scaler.ndim

0

In [198]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [199]:
vector.ndim

1

In [200]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [201]:
matrix.ndim

2

In [202]:
tensor = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [203]:
tensor.shape

torch.Size([1, 3, 3])

In [204]:
tensor.ndim

3

In [205]:
sword = torch.tensor(
    [[[[1,2],
       [3,4],
       [5,6]]]]
)
sword

tensor([[[[1, 2],
          [3, 4],
          [5, 6]]]])

In [206]:
sword.ndim

4

In [207]:
sword.shape

torch.Size([1, 1, 3, 2])

In [208]:
a = torch.tensor( [
    [ [1,2,3],
     [2,4,6],
      [3,6,9]],

    [ [3,2,1],
     [6, 4, 2],
      [9,6,3]]
])
a.shape

torch.Size([2, 3, 3])

In [209]:
# make a tensor of torch.Size([1,2,3])

b = torch.tensor([
    [
    [1,2,3],
    [4,5,6]
]
])
b.shape

torch.Size([1, 2, 3])

### why Random Tensors ?
Random tensors are important because the way neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [210]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [211]:
random_tensor.ndim

2

In [212]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size =(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [213]:
random_image_size_tensor

tensor([[[0.1053, 0.2695, 0.3588,  ..., 0.1481, 0.1733, 0.6659],
         [0.3514, 0.8087, 0.3396,  ..., 0.9274, 0.9477, 0.7935],
         [0.8777, 0.4331, 0.2249,  ..., 0.9902, 0.5978, 0.7888],
         ...,
         [0.7965, 0.7666, 0.8725,  ..., 0.1494, 0.1160, 0.7257],
         [0.2102, 0.0767, 0.9499,  ..., 0.6599, 0.7642, 0.1562],
         [0.9902, 0.5277, 0.5861,  ..., 0.4111, 0.9908, 0.8855]],

        [[0.5449, 0.1263, 0.6236,  ..., 0.2283, 0.8619, 0.7597],
         [0.5820, 0.1566, 0.1371,  ..., 0.1744, 0.3222, 0.5495],
         [0.7420, 0.3132, 0.6374,  ..., 0.6496, 0.5809, 0.2162],
         ...,
         [0.9435, 0.7362, 0.4158,  ..., 0.5498, 0.8349, 0.9400],
         [0.3117, 0.9626, 0.5265,  ..., 0.2752, 0.6565, 0.5912],
         [0.6687, 0.3950, 0.4023,  ..., 0.4438, 0.9989, 0.3017]],

        [[0.1901, 0.4283, 0.1539,  ..., 0.9442, 0.1459, 0.6084],
         [0.4032, 0.1417, 0.6007,  ..., 0.5106, 0.3808, 0.4320],
         [0.3945, 0.6757, 0.9492,  ..., 0.5638, 0.0656, 0.

### Creating random tensors with value 0 or 1

In [214]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [215]:
zeros = zeros + random_tensor
zeros

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [216]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [217]:
ones.dtype

torch.float32

### Creating a tensor range and tensors like other tensors

In [218]:
# Use torch.range()

# torch.range(1,100)
# works but it is deprecated. so, we'll use torch.arange

one_to_ten = torch.arange(start =0, end =11, step=1)

In [219]:
one_to_ten.shape

torch.Size([11])

In [220]:
# Creating tensors like
ten_zeros = torch.zeros_like(input =one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Dealing with Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [221]:
# Float 32 tensor
float_32_tensor = torch.tensor([4.0,5.0,2.0],
                               dtype=None, #What dataType is the tensor
                               device = None, # what device is your tensor on
                               requires_grad=False # whether or not to track gradients with the tensor operations
                               )

float_16_tensor = torch.tensor([1.2,3.1,5.5],
                               dtype= torch.float16, #What dataType is the tensor
                               device = None, # what device is your tensor on
                               requires_grad=False # whether or not to track gradients with the tensor operations
                               )
float_32_tensor

tensor([4., 5., 2.])

In [222]:
float_32_tensor.dtype

torch.float32

### Getting Tensor Attributes

In [223]:
float_16_tensor * float_32_tensor

tensor([ 4.8008, 15.4980, 11.0000])

In [224]:
int_32_tensor = torch.tensor([4,6,7], dtype=torch.int64)

In [225]:
float_32_tensor * int_32_tensor

tensor([16., 30., 14.])

### Getting Information from tensors
1. Tensors not right datatype -> to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape -> to get shape from tensor, can use `tensor.shape`
3. Tensors not on the right device -> to get device from a tensor, can use `tensor.device`

In [226]:
# create a tensor

some_tensor = torch.rand(2,4)
some_tensor

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002]])

In [227]:
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([2, 4])
cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication


In [228]:
# Create a tensor and perform basic arithmetic operations

tensor = torch.tensor([1,2,3])
print("Sum: ",tensor+10) #torch.sum(tensor,10)
print("Difference: ",tensor-1) #torch.diff(tensor,1)
print("Product: ",tensor*10) #torch.mul(tensor,10)
print("Division: ",tensor/2) #torch.divide(tensor,2)

Sum:  tensor([11, 12, 13])
Difference:  tensor([0, 1, 2])
Product:  tensor([10, 20, 30])
Division:  tensor([0.5000, 1.0000, 1.5000])


### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise Multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The `Inner Dimension` must match:

- `(3,2) & (3,2)` won't work
- `(3,2) & (2,3)` will work
- `(3,2) & (2,3)` will work

2. The resulting matrix has a shape of **outer dimensions**:
- `(2,3) & (3,2)` -> (2,2)
- `(3,2) & (2,3)` -> (3,3)

In [229]:
# Element wise multiplication
print("tensor * tensor")
print(tensor * tensor)

tensor * tensor
tensor([1, 4, 9])


In [230]:
# Matrix multiplication

print("tensor to tensor matrix multiplication")
print(torch.matmul(tensor,tensor))

tensor to tensor matrix multiplication
tensor(14)


In [231]:
m1 = torch.rand(2,3)
m2 = torch.rand(2,3)

print(m1)
print(m2)

tensor([[0.0351, 0.6826, 0.3743],
        [0.5220, 0.1336, 0.9666]])
tensor([[0.9754, 0.8474, 0.8988],
        [0.1105, 0.4563, 0.9719]])


In [232]:
# torch.matmul(m1,m2)
torch.matmul(m1,m2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [233]:
a = torch.rand(3,2)
b = torch.rand(2,3)
# If you notice you'll see, shape of two matrices. row of mat1 and column of mat2 is shape of matrix multiplication
torch.matmul(a,b)

tensor([[0.2564, 0.3298, 0.3051],
        [0.5817, 1.0402, 0.5033],
        [0.5574, 1.0042, 0.4774]])

### One of the most common errors in deep learning: Shape Errors

In [234]:
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]
])

# torch.matmul == torch.mm
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**

A transpose switches the axes or dimension of a given tensor

In [235]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [236]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [237]:
print(f"Original shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.T.shape}")

Original shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([2, 3])


In [238]:
torch.mm(tensor_A,tensor_B.T
         )

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [239]:
torch.mm(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

### finding the min, max, mean, sum, etc (Tensor Aggregation)

In [240]:
data = torch.arange(0,105,5)
# When datatype is not specified, it assigns Long and gives error which giving mean value.
data

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100])

In [241]:
print("min",data.min())
print("max",data.max())
print("mean", torch.mean(data.type(torch.float32)))
print("median",data.median())
print("min",data.sum())

min tensor(0)
max tensor(100)
mean tensor(50.)
median tensor(50)
min tensor(1050)


In [242]:
data.type(torch.float32).mean()

tensor(50.)

### Finding the Positional Min and Max of Tensors

In [243]:
# find the position in tensor that has the minimum value with argmin() -> returns index of min value from the tensor.
data.argmin()


tensor(0)

In [244]:
# find the position in tensor that has the maxiumu value with argmax() -> returns index of max value from the tensor.
data.argmax()


tensor(20)

### Reshaping, Viewing and stacking tensors
- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shapes but keep the same memory as the original tensor
- Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - remove all `1` dimension from a tensor
- Unsqueeze - add a `1` dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) into a certain way

In [245]:
#Let's create a tensor
x = torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [246]:
# Add an extra dimension
x_reshaped = x.reshape(1,5)

RuntimeError: shape '[1, 5]' is invalid for input of size 10

In [ ]:
x_reshaped = x.reshape(1,10)
x_reshaped

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [247]:
# change the view
z = x.view(1,10)
z,z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [248]:
# Changing z changes x (because a view of tensor shares the same memory as the original input)
z[:,0] =5
z,x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [249]:
# Stack tensors on top of each other
# x_stacked = torch.stack([x,x,x,x], dim=2)
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [250]:
a = torch.arange(1,10)
a, a.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [251]:
a = a.reshape(1,9)
a, a.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [252]:
# torch.squeeze() -> removes all single dimensions from a target tensor

In [253]:
print(f"Previous tensor: {a}")
print(f"Previous shape: {a.shape}")
print("")
a_squeezed = a.squeeze()
print(f"New tensor: {a_squeezed}")
print(f"New shape: {a_squeezed.shape}")

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [254]:
# torch.unsqueeze() - adds a single dimension a target at a specific dim (dimension)
a_unsqueeze = a_squeezed.unsqueeze(dim=0)

print(f"Previous tensor: {a_squeezed}")
print(f"Previous shape: {a_squeezed.shape}")
print("")
print(f"New tensor: {a_unsqueeze}")
print(f"New shape: {a_unsqueeze.shape}")

Previous tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [255]:
### torch.permute - rearrange the dimension of tensor in a specific order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# permute the original tensor to rerrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->2, 1->0 and 2->1

# print(f"Previous tensor: {x_original}")
print(f"Previous tensor shape: {x_original.shape}")

# print(f"\nNew tensor: {x_permuted}")
print(f"New tensor shape: {x_permuted.shape}")

Previous tensor shape: torch.Size([224, 224, 3])
New tensor shape: torch.Size([3, 224, 224])


### Selecting data from the tensor (Indexing)

indexing with pyTorch is similar to indexing with Numpy.

In [256]:
x = torch.arange(1,126).reshape(5,5,5)
x,x.shape

(tensor([[[  1,   2,   3,   4,   5],
          [  6,   7,   8,   9,  10],
          [ 11,  12,  13,  14,  15],
          [ 16,  17,  18,  19,  20],
          [ 21,  22,  23,  24,  25]],
 
         [[ 26,  27,  28,  29,  30],
          [ 31,  32,  33,  34,  35],
          [ 36,  37,  38,  39,  40],
          [ 41,  42,  43,  44,  45],
          [ 46,  47,  48,  49,  50]],
 
         [[ 51,  52,  53,  54,  55],
          [ 56,  57,  58,  59,  60],
          [ 61,  62,  63,  64,  65],
          [ 66,  67,  68,  69,  70],
          [ 71,  72,  73,  74,  75]],
 
         [[ 76,  77,  78,  79,  80],
          [ 81,  82,  83,  84,  85],
          [ 86,  87,  88,  89,  90],
          [ 91,  92,  93,  94,  95],
          [ 96,  97,  98,  99, 100]],
 
         [[101, 102, 103, 104, 105],
          [106, 107, 108, 109, 110],
          [111, 112, 113, 114, 115],
          [116, 117, 118, 119, 120],
          [121, 122, 123, 124, 125]]]),
 torch.Size([5, 5, 5]))

In [257]:
x[0,1,2]

tensor(8)

In [258]:
y = torch.arange(1,10).reshape(1,3,3)

# Get all values of  0th and 1st dimensions but only index 1 and 2nd dimension
print(y[:, :,1])

# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
print(y[:,1,1])

# Get index 0 of 0th and last dimension and all values of 2nd dimension
print(y[0,0,:])

#index on y to return 9
print(y[0,2,2])

# index on y to return 3,6,9
print(y[0,:,2])

tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])
tensor(9)
tensor([3, 6, 9])


### PyTorch tensor and Numpy
Numpy is a popular scientific python numerical library and because of this, PyTorch has functionality to interact with it. 
- Data in numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`


- By default numpy array creates an array of `float64` whereas tensor creates a tensor of `torch.float32`

- you can use `tensor.type()` method to change the datatype.

In [259]:
# Numpy array to tensor
import numpy as np

array = np.arange(1.0,10.0)
# tensor =torch.arange(1.0,10.0)
tensor = torch.from_numpy(array)
array.dtype, tensor.dtype

#Warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float 64 unless specified otherwise

(dtype('float64'), torch.float64)

In [260]:
# Change the value of array, what will this do to `tensor` ?
# Ans -> No, It won't change tensor.
array = array+1
array,tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [261]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,tensor.dtype, numpy_tensor, numpy_tensor.dtype


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [262]:
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### PyTorch REPRODUCIBILITY (taking the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ....`

To reduce the randomness in neural network and PyTorch comes the concept of **random seed.**
Essentially what the random seed does is `flavour` the randomness.

In [263]:
RANDOM_SEED = 42

In [264]:
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Runing tensors and pyTorch objects on the GPUs (and making faster computations)

GPU = faster computation on numbers, thanks to CUDA + Nvidia hardware + PyTorch working behind the scenes top make everything good.

### 1. Getting CPU

1. Easiest - Use Google Colab for free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and require he investment of purchasing a GPU, theres lot of options...
3. Use cloud computing - GCP, AWS, Azure, these services allows you to rent computers on the cloud and access them.

For 2,3 Pytorch +GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation.

### 2. Check for GPU access with PyTorch

In [265]:
torch.cuda.is_available()

False

In [266]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [267]:
# count number of devices
torch.cuda.device_count()

0

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on "gpu" if available, else default to "cpu"

### 3. Putting tensors (and models) on GPU
the reason we want our tensors/models on GPU is because using a GPU results in faster computations.

In [268]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [269]:
#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### Moving tensors back to the CPU
- if tensor is on the GPU, can't transform it to Numpy
`tensor_on_gpu.numpy()`
- this is working because my device is "cpu" not "gpu", otherwise it would give an error.

In [270]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_gpu =  tensor_on_gpu.cpu().numpy()
tensor_back_on_gpu

array([1, 2, 3])

### PyTorch Fundamentals: (Exercise and Extra Curriculam)
See exercies for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercise