In [44]:
from torchvision import datasets
from torchvision.transforms import ToTensor

In [45]:
train_data = datasets.MNIST (
    root = 'data',
    train= True,
    transform= ToTensor(),
    download= True
)

test_data = datasets.MNIST (
    root = 'data',
    train= False,
    transform= ToTensor(),
    download= True
)

In [46]:
train_data

Dataset MNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [47]:
test_data

Dataset MNIST
    Number of datapoints: 10000
    Root location: data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [48]:
train_data.data

tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0,

In [49]:
train_data.data.shape

torch.Size([60000, 28, 28])

In [50]:
test_data.data

tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0,

In [51]:
test_data.data.shape

torch.Size([10000, 28, 28])

In [52]:
train_data.targets

tensor([5, 0, 4,  ..., 5, 6, 8])

In [53]:
from torch.utils.data import DataLoader

loaders = {
    'train': DataLoader(
        train_data,
        batch_size=100,
        shuffle=True,
        num_workers=1,
    ),

    'test': DataLoader(
        test_data,
        batch_size=100,
        shuffle=False,
        num_workers=1,
    )

}

In [54]:
loaders

{'train': <torch.utils.data.dataloader.DataLoader at 0x209c04ac160>,
 'test': <torch.utils.data.dataloader.DataLoader at 0x209b7bea140>}

In [55]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        self.conv1 = nn.Conv2d(1,10, kernel_size=5)
        self.conv2 = nn.Conv2d(10,10, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fcl = nn.Linear(160,50)
        self.fcl2 = nn.Linear(50,10)
    
    def forward(self,x):
        x = F.relu(F.max_pool2d(self.conv1(x),2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)),2))
        x = x.view(x.size(0), -1)
        x = F.relu(self.fcl(x))
        x = F.dropout(x, training=self.training)
        x = self.fcl2(x)
        return x


In [58]:
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = CNN().to(device)
optimizer = optim.Adam(model.parameters(), lr = 0.001)
loss_fn = nn.CrossEntropyLoss()

def train(epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(loaders['train']):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = loss_fn(output,target)
        loss.backward()
        optimizer.step()

        if batch_idx % 20 == 0:
            print(f"Train Epoch: {epoch} [{batch_idx * len(data)}/{len(loaders['train'].dataset)} ({100. * batch_idx / len(loaders['train']):.0f}%)]\tLoss: {loss.item():.6f}")

def test():
    model.eval()

    test_loss =0
    correct =0

    with torch.no_grad():
        for data, target in loaders['test']:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss += loss_fn(output,target).item()
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(loaders['test'].dataset)
    print(f"\nTest set: Average loss: {test_loss:.4f}, Accuracy: {correct}/{len(loaders['test'].dataset)} ({100. * correct / len(loaders['test'].dataset):.0f}%)\n")


In [59]:
for epoch in range(1,11):
    train(epoch)
    test()

Train Epoch: 1 [0/60000 (0%)]	Loss: 2.284055
Train Epoch: 1 [2000/60000 (3%)]	Loss: 2.172488
Train Epoch: 1 [4000/60000 (7%)]	Loss: 1.849210
Train Epoch: 1 [6000/60000 (10%)]	Loss: 1.552618
Train Epoch: 1 [8000/60000 (13%)]	Loss: 1.247236
Train Epoch: 1 [10000/60000 (17%)]	Loss: 0.907414
Train Epoch: 1 [12000/60000 (20%)]	Loss: 0.872080
Train Epoch: 1 [14000/60000 (23%)]	Loss: 0.762458
Train Epoch: 1 [16000/60000 (27%)]	Loss: 0.934909
Train Epoch: 1 [18000/60000 (30%)]	Loss: 0.837893
Train Epoch: 1 [20000/60000 (33%)]	Loss: 0.735463
Train Epoch: 1 [22000/60000 (37%)]	Loss: 0.744545
Train Epoch: 1 [24000/60000 (40%)]	Loss: 0.875852
Train Epoch: 1 [26000/60000 (43%)]	Loss: 0.565514
Train Epoch: 1 [28000/60000 (47%)]	Loss: 0.535749
Train Epoch: 1 [30000/60000 (50%)]	Loss: 0.642980
Train Epoch: 1 [32000/60000 (53%)]	Loss: 1.019198
Train Epoch: 1 [34000/60000 (57%)]	Loss: 0.540629
Train Epoch: 1 [36000/60000 (60%)]	Loss: 0.702305
Train Epoch: 1 [38000/60000 (63%)]	Loss: 0.649352
Train Epoch