In [1]:
import tensorflow as tf

In [3]:
a = tf.constant(7)
b = tf.constant([1,3,5])
c = tf.constant([[1,3,5],[2,4,6]])
print(f"{a}\n\n {b}\n\n{c}")

7

 [1 3 5]

[[1 3 5]
 [2 4 6]]


In [4]:
x = tf.constant([1,2,3],dtype=tf.float32)
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [5]:
zeros = tf.zeros((2,3))
ones = tf.ones((3,2))
random = tf.random.normal((2,2))
print(f"{zeros}\n\n {ones}\n\n{random}")

[[0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1.]
 [1. 1.]
 [1. 1.]]

[[-0.65172523  1.9869826 ]
 [ 0.5882047   0.6508017 ]]


In [7]:
print(f"{random.shape}, {random.dtype}, {tf.rank(random)}")

(2, 2), <dtype: 'float32'>, 2


In [10]:
p = tf.constant([[1,2],[3,4]])
q = tf.constant([[4,3],[2,1]])
print("Matrix Multiplication: ",tf.matmul(p,q))
print("Element wise mulitplication: ",(p*q))

Matrix Multiplication:  tf.Tensor(
[[ 8  5]
 [20 13]], shape=(2, 2), dtype=int32)
Element wise mulitplication:  tf.Tensor(
[[4 6]
 [6 4]], shape=(2, 2), dtype=int32)


In [11]:
x = tf.constant([[1,2,3]],dtype=tf.float32) # (1*3)
w = tf.constant([0.5,0.5,0.5]) # (3,)

x*w

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.5, 1. , 1.5]], dtype=float32)>

In [13]:
## VVI
x = tf.constant([1,2,3,4])
print(tf.reshape(x,(2,2)))
print(tf.cast(x,tf.float32))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [15]:
import numpy as np
# Numpy to tensorflow
n = np.array([1,3,5])
t = tf.convert_to_tensor(n)
print(t)
t.numpy()

tf.Tensor([1 3 5], shape=(3,), dtype=int64)
[1 3 5], dtype=int64
